// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shop_Project.Data;

#nullable disable

namespace Shop_Project.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Shop_Project.Models.Category", b =>
                {
                    b.Property<int>("C_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("C_id"));

                    b.Property<string>("C_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("C_id");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("Shop_Project.Models.Complaint", b =>
                {
                    b.Property<int>("Cm_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Cm_id"));

                    b.Property<string>("Cm_description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Cm_reply")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("S_id")
                        .HasColumnType("int");

                    b.HasKey("Cm_id");

                    b.ToTable("Complaint");
                });

            modelBuilder.Entity("Shop_Project.Models.Customer", b =>
                {
                    b.Property<int>("Cu_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Cu_id"));

                    b.Property<string>("Cu_name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Cu_ph")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Cu_id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Shop_Project.Models.Employee", b =>
                {
                    b.Property<int>("E_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("E_id"));

                    b.Property<string>("E_email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("E_name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("E_ph")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("E_position")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("S_id")
                        .HasColumnType("int");

                    b.HasKey("E_id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Shop_Project.Models.Expense", b =>
                {
                    b.Property<int>("Ex_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Ex_id"));

                    b.Property<string>("Ex_amount")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ex_date")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ex_type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("S_id")
                        .HasColumnType("int");

                    b.HasKey("Ex_id");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("Shop_Project.Models.Login", b =>
                {
                    b.Property<int>("L_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("L_id"));

                    b.Property<string>("S_Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("S_id")
                        .HasColumnType("int");

                    b.Property<string>("S_shopcode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("S_type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("L_id");

                    b.ToTable("Login");
                });

            modelBuilder.Entity("Shop_Project.Models.Notification", b =>
                {
                    b.Property<int>("N_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("N_id"));

                    b.Property<string>("N_date")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("N_description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("N_id");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Shop_Project.Models.Order", b =>
                {
                    b.Property<int>("O_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("O_id"));

                    b.Property<string>("O_date")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("O_quantity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("O_status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("P_id")
                        .HasColumnType("int");

                    b.Property<int>("S_id")
                        .HasColumnType("int");

                    b.HasKey("O_id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Shop_Project.Models.Product", b =>
                {
                    b.Property<int>("P_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("P_id"));

                    b.Property<int>("C_id")
                        .HasColumnType("int");

                    b.Property<string>("P_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("P_price")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("S_id")
                        .HasColumnType("int");

                    b.HasKey("P_id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Shop_Project.Models.Request", b =>
                {
                    b.Property<int>("R_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("R_id"));

                    b.Property<string>("R_description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("R_reply")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("S_id")
                        .HasColumnType("int");

                    b.HasKey("R_id");

                    b.ToTable("Requests");
                });

            modelBuilder.Entity("Shop_Project.Models.Sales", b =>
                {
                    b.Property<int>("Sl_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Sl_id"));

                    b.Property<int>("Cu_id")
                        .HasColumnType("int");

                    b.Property<int>("P_id")
                        .HasColumnType("int");

                    b.Property<int>("S_id")
                        .HasColumnType("int");

                    b.Property<string>("Sl_date")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Sl_id");

                    b.ToTable("Sales");
                });

            modelBuilder.Entity("Shop_Project.Models.Shop_details", b =>
                {
                    b.Property<int>("S_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("S_id"));

                    b.Property<string>("S_Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("S_PH")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("S_location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("S_id");

                    b.ToTable("Shop_Details");
                });
#pragma warning restore 612, 618
        }
    }
}
